// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdOC6dL8ud4c4K-3UD1AyesI7JJMAs3mU',
    appId: '1:788748570407:web:effe4b588a25da55a76302',
    messagingSenderId: '788748570407',
    projectId: 'bsnstat-84d66',
    authDomain: 'bsnstat-84d66.firebaseapp.com',
    storageBucket: 'bsnstat-84d66.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7axAL6z0xT-6yVdClVdSVSHArWrn8RJo',
    appId: '1:788748570407:android:1d8bca45ec4d5e0fa76302',
    messagingSenderId: '788748570407',
    projectId: 'bsnstat-84d66',
    storageBucket: 'bsnstat-84d66.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgl_rj-Ff8WbXxxPYL1X-vIDusZadIxLc',
    appId: '1:788748570407:ios:8176298739829a27a76302',
    messagingSenderId: '788748570407',
    projectId: 'bsnstat-84d66',
    storageBucket: 'bsnstat-84d66.appspot.com',
    iosBundleId: 'com.example.bsnstat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgl_rj-Ff8WbXxxPYL1X-vIDusZadIxLc',
    appId: '1:788748570407:ios:40f8bcee8715e690a76302',
    messagingSenderId: '788748570407',
    projectId: 'bsnstat-84d66',
    storageBucket: 'bsnstat-84d66.appspot.com',
    iosBundleId: 'com.example.bsnstat.RunnerTests',
  );
}
